### ISSUE TITLE
Final Project Submission Feedback

### ISSUE THREAD

**Issue by EmanHerawy** [dapsavoie/blockchain-developer-bootcamp-final-project#1]
Thanks for your submission for Final Project Submission in Blockchain Developer Bootcamp 2021. It didn't quite meet the requirements for the Final Project but you're really close! If you fix the things below you can get a certification in January. Here's what we see missing:
- Your project needs five smart contract tests that we can easily run locally
 but when we tried to test, her's what we got 
![image](https://user-images.githubusercontent.com/10674070/145285701-2027d905-6760-4101-8392-3265eba659a3.png)

If you'd like to fix this thing, you can resubmit your Final Project. Most likely, we'll have to revisit it in January. But you're really close! Don't give up.
Before resubmitting, be sure to run it by a friend and see if they can interact with your project on the baseline requirements. Please ping coogan.brennan@consensys.net when you believe you corrected the errors.
Thank you,

**Comment by dapsavoie** [comment]
iv e fixed this :)and emailled coogan but no response
